services:
  ds2api:
    image: crpi-cnazxqmg4avmg4fq.cn-beijing.personal.cr.aliyuncs.com/ronghuaxueleng/ds2api:latest
    container_name: ds2api
    restart: always
    ports:
      - "6011:5001"
    volumes:
      - ./config.json:/app/config.json    # 配置文件
      - ./.env:/app/.env                  # 环境变量
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=INFO
      - DS2API_ADMIN_KEY=${DS2API_ADMIN_KEY:-ds2api}
